### PR TITLE
feat: Added deref function

### PR DESCRIPTION
**Pull request by jkyte-ccc**

### CODE REVIEW

**Comment by jwatson-ccc** [comment]
@jkyte-ccc 

I am curious about the utility of the `Deref()` function. It appears to dereference a pointer, and if the pointer is null, the zero value of that type is returned. This behavior seems to suggest that the value being passed in really should not be a pointer in the first place.

Where did we run into a use-case for this function?

**Comment by jkyte-ccc** [comment]
> @jkyte-ccc
> 
> I am curious about the utility of the `Deref()` function. It appears to dereference a pointer, and if the pointer is null, the zero value of that type is returned. This behavior seems to suggest that the value being passed in really should not be a pointer in the first place.
> 
> Where did we run into a use-case for this function?

@jwatson-ccc 

In the extractor, there's a few instances where it was used such as when a boolean type is used in the spanner instance, but in redshift, they have the value as a nullable varchar that was `OPEN`, `CLOSED`, or `NULL`.

I think there could also be some instances where this would be useful, so that we don't always have to do `if val != nil` checks before using a pointer

**Comment by jwatson-ccc** [comment]
> @jwatson-ccc
> 
> In the extractor, there's a few instances where it was used such as when a boolean type is used in the spanner instance, but in redshift, they have the value as a nullable varchar that was `OPEN`, `CLOSED`, or `NULL`.
> 
> I think there could also be some instances where this would be useful, so that we don't always have to do `if val != nil` checks before using a pointer

@jkyte-ccc 

In that scenario, it would be appropriate to use the `sql.NullString` type instead of a `*string`. 

I feel that a situation that needs a `Defref()` function is a bit of a code smell that should be fixed. 

Putting this into the standard library would promote its usage...

**Comment by jkyte-ccc** [comment]
> > @jwatson-ccc
> > In the extractor, there's a few instances where it was used such as when a boolean type is used in the spanner instance, but in redshift, they have the value as a nullable varchar that was `OPEN`, `CLOSED`, or `NULL`.
> > I think there could also be some instances where this would be useful, so that we don't always have to do `if val != nil` checks before using a pointer
> 
> @jkyte-ccc
> 
> In that scenario, it would be appropriate to use the `sql.NullString` type instead of a `*string`.
> 
> I feel that a situation that needs a `Defref()` function is a bit of a code smell that should be fixed.
> 
> Putting this into the standard library would promote its usage...

@jwatson-ccc 

That makes sense. I can close this PR

**Pull request closed without merging**
